server:
  port: 8080
  servlet:
    session:
      cookie:
        # 避免与本地启动authorizationserver默认的cookie名称：JSESSIONID冲突
        name: UISESSIONCOUPON
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          authorizationserver:
            client-id: client-for-server
            client-secret: client-for-server
            provider: authorizationserver
            client-name: 使用自定义授权服务器登录
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            scope: profile,email,phone
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          authorizationserver:
            authorization-uri: http://localhost:9999/oauth/authorize
            token-uri: http://localhost:9999/oauth/token
            user-info-uri: http://localhost:9999/me
            user-name-attribute: "name"
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json




            #spring:
            #  thymeleaf:
            #    cache: false
            #  security:
            #    oauth2:
            #      client:
            #        registration:
            #          github:
            #            client-id: b7fb29a538bb19b09365
            #            client-secret: 2fbfd22e69e61d873bad55143538770748a76d3a
            #          tdf:
            #            client-id: tdfOauth2SSO213
            #            client-secret: 123456
            #            provider: tdf
            #            client-name: 太极统一认证
            #            authorization-grant-type: authorization_code
            #            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            #        provider:
            #          tdf:
            #            authorization-uri: http://localhost:9999/oauth/authorize
            #            token-uri: http://localhost:9999/oauth/token
            #            user-info-uri: http://localhost:9999/user/me
            #            user-name-attribute: "name"
            #            jwk-set-uri: http://localhost:9999/.well-known/jwks.json